### ISSUE TITLE
Pare down README to general info

### ISSUE THREAD

**Issue by talexand** [getsubrosa/subrosa#21]
The README is carrying a lot of information subject to fast revision or not a product of contributor consensus. Additionally, it doesn't have all the main information to get started with playing with/using the project.

This makes it difficult for people to get a technical user overview of the project/repo. The README should be pared down to the above desirable minima.

**Comment by ryankanno** [comment]
Cleaned up in dcb79d2808b6f2589d4a3921bef447bd8c45555d

**Comment by talexand** [comment]
Wonderful; looks good.
