### ISSUE TITLE
sshd configuration prevents ansible access

### ISSUE THREAD

**Issue by ryankanno** [getsubrosa/subrosa#22]
The sshd configuration prevents being able to run `vagrant up` in consecutive runs.  Configuration needs to be tweaked to allow ansible back into the box.

**Comment by talexand** [comment]
Is this the source of the message that goes like, "Run `vagrant provision` to perform X" after it's been put up once?

**Comment by ryankanno** [comment]
Basically, the sshd_config we're deploying doesn't have sftp subsystem enabled. Ansible expects this to drop files and hence broke the provisioner's ability to update. Fixed in b8bcad96bd0d4414baacc0c62e612c9ed88d035e
