### ISSUE TITLE
MVP component selection: mail server

### ISSUE THREAD

**Issue by talexand** [getsubrosa/subrosa#5]
- [ ] MTA
- [ ] POP/IMAP server
- [ ] Webmail

**Comment by nh-github** [comment]
* Mail serving:
  * SMTP: Postfix
  * IMAP/POP: Dovecot
* additional
  * Webmail: Roundcube (backup: squirrelmail, alt: horde, zimbra)
  * search: Solr
  * DNSBL
  * Mobile push: Z-Push
  * DSPAM
  * Postgrey
  * OpenDKIM
  * client autoconfig

**Comment by nh-github** [comment]
I didn't add backup/alt listing for:
SMTP: backup: Exim, alt: OpenSMTPD, Courier
IMAP: backup: Cyrus, alt: Courier

**Comment by ryankanno** [comment]
My vote is for Postfix / Dovecot.

**Comment by nh-github** [comment]
Great!  Assuming no objections to those (everything under additional is still optional/open), shall we start from: debops.postfix, al3x/sovereign [postfix], or scratch.  For IMAP, crib from sovereign or just start from scratch (aptitude install dovecot-imapd dovecot-ldap dovecot-lmtpd dovecot-managesieved dovecot-sieve dovecot-solr dovecot-sqlite)?

**Comment by talexand** [comment]
Who's taking this one up? It *looks* like nh is volunteering.

**Comment by nh-github** [comment]
*ducks*

**Comment by ryankanno** [comment]
I say let's just look at the various implementations and where it makes sense, let's just standardize on configurations.

**Comment by talexand** [comment]
Sorry, for clarity, could you list which is the MTA here?

**Comment by nh-github** [comment]
MTA: Postfix

**Comment by talexand** [comment]
Thanks.
